
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int l_PAPANOEL = 15;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int SEMI = 2;
  public static final int IDENTIFIER = 11;
  public static final int LPAREN = 7;
  public static final int BOOLEAN = 17;
  public static final int EOF = 0;
  public static final int NUMBER = 9;
  public static final int BREAK = 16;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int INTEGER_LITERAL = 12;
  public static final int EQEQ = 14;
  public static final int NAVIDAD = 10;
  public static final int UMINUS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "NAVIDAD",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "EQ",
  "EQEQ",
  "l_PAPANOEL",
  "BREAK",
  "BOOLEAN"
  };
}

